os: osx
language: swift
osx_image: xcode11
xcode_workspace: EP QTc.xcworkspace
xcode_scheme: EP QTc
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone XR
before_install:
  - gem install cocoapods --pre
  - pod install --repo-update
  - pwd
  - ls -R
 
